language: generic

os: linux
dist: focal

cache:
    directories:
        - $HOME/.local/share/fonts/JetBrainsMono
        - $HOME/.cargo/bin

jobs:
    include:
        - stage: install tectonic
          install:
          - sudo apt-get -y install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev cargo
          script:
          - cargo install tectonic

        - stage: install JetBrainsMono
          install:
          - wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
          script:
          - mkdir -p $HOME/.local/share/fonts/JetBrainsMono
          - unzip -d $HOME/.local/share/fonts/JetBrainsMono JetBrainsMono.zip
          - fc-cache -f -v

        - stage: compile
          before_script:
          - sudo apt-get -y install ttf-dejavu libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev
          script:
          - $HOME/.cargo/bin/tectonic main.tex

        - stage: deploy to github
          deploy:
            provider: releases
            token: $GITHUB_TOKEN
            file: ./main.pdf
            cleanup: true
            on:
                tags: true
